config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  get "/flats", to: "flats#index", as: :flats


  get "flats/:id", to: "flats#show", as: :flat

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'
require 'json'

class FlatsController < ApplicationController
  before_action :set_flats, only: [:index, :show]

  def index; end

  def show
    @flat = @flats.find { |flat| flat["id"] == params[:id].to_i }
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    response = open(url).read
    @flats = JSON.parse(response)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All flats:</h1>

<ul>
  <% @flats.each do |flat| %>

  <li>
    <%= link_to flat["name"], flat_path(flat["id"]) %> - <%= flat["price"] %> <%= flat["priceCurrency"] %>
  </li>

  <% end %>
</ul>

app/views/flats/show.html.erb
<h1> <%= @flat["name"] %> </h1>
<h2> <%= @flat["price"] %> <%= @flat["priceCurrency"] %> </h2>

<img style="width: 60%; height: 400px; margin: 0 200px;" src=" <%= @flat['imageUrl'] %> " alt="">


<%= link_to "Go back", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StaticBnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>